Sources/SATSCore/Components/TopBar/TopBar.swift

autolayout was complaining due to a conflicting constraint error, which
was due mostly due constraints that UIStackView makes.
Given that UIStackView is not doing much in this particular view I opted
to removed it from the internal implementation.
This doesn't change anything from the API or behavior of the component.

Fix layout issue in TopBar

---

Package.resolved
Sources/SATSCore/Assets/Colors.xcassets/Main/CTA/ctaDisabled.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/Main/Secondary/secondaryDisabled.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/On/Clean/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/On/Clean/onClean.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/On/Clean/onCleanDisabled.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/Signal/signalWarning.colorset/Contents.json
Sources/SATSCore/Assets/ThemeColors.xcassets/Blue Theme/Primary/bluePrimaryDisabled.colorset/Contents.json
Sources/SATSCore/Assets/ThemeColors.xcassets/Gold Theme/Primary/goldPrimaryDisabled.colorset/Contents.json
Sources/SATSCore/Assets/ThemeColors.xcassets/Platinum Theme/Primary/platinumPrimaryDisabled.colorset/Contents.json
Sources/SATSCore/Assets/ThemeColors.xcassets/Silver Theme/Primary/silverPrimaryDisabled.colorset/Contents.json
Sources/SATSCore/BasicComponents/SATSButton/SATSButton-Style.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton.swift
Sources/SATSCore/DNA/Colors/ColorName.swift
Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift
Sources/SATSCore/DNA/Colors/UIKit-Color.swift
Tests/SATSCoreTests/ColorsTests.swift

- Add `.onClean` and `.onCleanDisabled` colors
- Update signal warning to '#946A00'
- Set disabled colors to `#E8E9EC`  as specified in Figma
- Use `.onClean` colors in the `.clean` buttons style

Improvement: update colors

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp/Views/Components/ErrorView/ErrorDemoView.swift
DemoApp/DemoApp/Views/ContentView.swift
Sources/SATSCore/Components/ErrorView/ErrorView.swift

I moved the ErrorView from the app to SATSCore as it should live in here.
I did some changes to the original API of it and the internal implementation.
In relation to the previous API, the changes are:
- No `compactLayout` option. This is not necessary as this view will take the
size of the parent, so it can be full screen or whitin a smaller module.
- Use `configure(with:)` instead of `configure(title:message)`. The main reason
for this is that we also have a `canRetry` boolean, with a default value of
`true`.
What we want here is that whenever `canRetry` is `true` the view will show a
"Retry" button.
- Change `retryTapped: (() -> Void)?` to `onRetry: (() -> Void) = {}`. This
delegate-like method has a default empty implementation. Previously we used
the optionality of this property to …

Component: ErrorView

---

Package.swift
Sources/SATSCore/Components/LoadingView/LoadingView.swift
Sources/SATSCore/DNA/Colors/ColorTheme-SwiftUI.swift
Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift
Sources/SATSCore/DNA/Font/SATSFont-SwiftUI.swift
Sources/SATSCore/DNA/Icons/SwiftUI-Icon.swift
Sources/SATSCore/Extensions/SwiftUI/Representable/ShareSheet.swift
Sources/SATSCore/Extensions/SwiftUI/Representable/SimpleRepresentable.swift
Sources/SATSCore/Extensions/SwiftUI/View-ConditionalModifier.swift

As we did with the main app. Now we don't need to keep supporting iOS 12
anymore.

Internal: bump SATSCore to iOS 13+

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp/App/DemoAppApp.swift
DemoApp/DemoApp/Views/BasicComponents/CustomAsyncImageDemoView.swift
DemoApp/DemoApp/Views/ContentView.swift
README.md
Sources/SATSCore/BasicComponents/CustomAsyncImage/CustomAsyncImage.swift
Sources/SATSCore/BasicComponents/CustomAsyncImage/ImageClient.swift
Sources/SATSCore/BasicComponents/CustomAsyncImage/ImageViewData.swift
Sources/SATSCore/BasicComponents/CustomAsyncImage/ImageViewModel.swift
Sources/SATSCore/Config.swift

After seeing how the `ViewModels` within the main app get complicated by having to fetch all nested structure's images
to be able to create the `ViewData` values I decided to clean up and refine the `CustomAsyncImage`[^1] I showed you before.
This implementation was inspired by the iOS 15 `AsyncImage` component.
You use it like this
```swift
CustomAsyncImage(.remote(url: url)) { image in
image
.resizable()
.aspectRatio(contentMode: .fit)
.frame(width: 200, height: 200)
.background(Color.red)
}
```
The "trick" is that the value for this component is a value of type: `ImageViewData`, which has the following cases
```swift
public enum ImageViewData: Equatable {
case empty
case remote(url: URL)
case loading
case image(_ image: Image)
}
```
So we can represent URLs as async images through …

Feature: `CustomAsyncImage` component

---

DemoApp/DemoApp/Views/BasicComponents/CustomAsyncImageDemoView.swift
Sources/SATSCore/BasicComponents/CustomAsyncImage/CustomAsyncImage.swift
Sources/SATSCore/BasicComponents/CustomAsyncImage/ImageViewData.swift

- Fix updating the custom image demo view and write explanation
- Make `CustomAsyncImage` iOS 14+ by using `@StateObject`
This undoes the choices done in a9f062a7e2940f6dc07890aa0a059db7c8f7a32f
The main reason for this is that as I'm getting a better understanding of how
SwiftUI works I realized that the `ImageViewModel` instance lifecycle must be
tied to the existence of `CustomAsyncImage` so when the image is fetched
asynchronously we update the view correctly.
SwiftUI can call the `init` method of views many times, creating multiple
values for the same view, so the way the initializer worked meant that
multiple
`ImageViewModel` instance were gonna be created, even though when that happen
we didn't duplicate network request, when the request returned
_we didn't update the image …

Fix: `CustomAsyncImage` data retention

---

Sources/SATSCore/BasicComponents/SATSButton/SATSButton-SwiftUI.swift
Sources/SATSCore/Extensions/SwiftUI/View-Utilities.swift
Sources/SATSCore/Extensions/SwiftUI/View-iOS13.swift
Sources/SATSCore/Extensions/UIKit/CGFloat-Utilities.swift

- Make `.satsButton` available for iOS 13
- Add `View.compatibleIgnoreSafeArea` to unify both iOS 13 and 14 APIs to achieve this. Later when we drop iOS 13 we can safely drop this method as this is a transition convenience
- Add `View.frame(size:)` to make frames with same width/height
- Add `.standardHorizontalPadding` to treat the 20pts from the horizontal margin as a constant

Internal: iOS13 conveniences

---

Sources/SATSCore/BasicComponents/SATSButton/SATSButton-Size.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton-SwiftUI.swift

The buttons would previously change between the loading and text states, now that's solved
Also we have now perfectly rounded buttons with `clipShape(Capsule())` instead of manually setting the corner radius as that was not a solid approach
| ![old](https://user-images.githubusercontent.com/167989/125935838-449215f0-483d-4f82-a7c7-607b52189cbd.gif) | ![new](https://user-images.githubusercontent.com/167989/125935853-0ea3935c-7f17-4786-a840-29c5953e9a30.gif) |

Improvement: Layout of Swift UI buttons when loading

---

Sources/SATSCore/DataStructures/IdentifiableList.swift
Tests/SATSCoreTests/IdentifiableListTests.swift

When using SwiftUI and lists with values that can update their state
like a `isLoading` property. We wanted to use a `Set` as a backing data
structure, as an Array would mean that every time we want to mutate a
given value, we need to find its index first.
`Set` uses `Hashable` and `Equatable` conformances to determine if a
given element is present on the list.
In `SwiftUI` it's common to use the `Identifiable` for elements in a
list, so SwiftUI will update them correctly.
In general swiftUI required 2 properties to see if the UI needs to be
refreshed or not:
1. Is the value the same (by ID)
2. Is the value the same (by values)
For this reason, we cannot use a custom `Equatable` conformance for
values that have an identity which value changes.
Then I decided to create a simple structure …

Feature: `IdentifiableList` Data Structure.

---

Sources/SATSCore/Extensions/SwiftUI/ViewData/ActionSheetViewData.swift
Sources/SATSCore/Extensions/SwiftUI/ViewData/AlertViewData.swift

`Alert` and `ActionSheet` in SwiftUI are structs, but from the view model perspective it's not easy to work with them
once we create an `Alert` value, we cannot inspect its properties. It's title and so on.
Then following the patterns of `ViewData` I created `AlertViewData` and `ActionSheetViewData` to work with them.
I also added some convenience initializers for `Alert` and `ActionSheet` that take their view data variants.

Feature: view data for alerts and action sheets

---

Sources/SATSCore/DataStructures/IdentifiableList.swift

- Ensure we only `update` an element if it's present in `IdentifiableList`
- Add `IdentifiableList#contains` method
To as a set, figure out if an element is included in the list or not (by id)

Improvement: identifiable list behaviors

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp/Views/Components/PullToRefreshContainer/PullToRefreshContainerDemoView.swift
DemoApp/DemoApp/Views/ContentView.swift
Sources/SATSCore/Components/PullToRefreshContainer/PullToRefreshContainer.swift

This is a custom way to implement "pull to refresh" for swiftUI in apps.
This should only be used for iOS 14, as iOS 15 gives support to SwiftUI to
use this natively.

Feature: `PullToRefreshContainer` component

---

Sources/SATSCore/Extensions/SwiftUI/Representable/SimpleControllerRepresentable.swift

A way to create a view controller to be used in SwiftUI
Example:
```swift
// with no parameters
SimpleControllerRepresentable(MyViewController.init)
// with parameters
SimpleControllerRepresentable { MyViewController(frame: .zero) }
```

Feature: Add `SimpleControllerRepresentable`

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp/Views/Components/NoticeView/NoticeDemoView.swift
DemoApp/DemoApp/Views/ContentView.swift
Sources/SATSCore/Components/NoticeView/Notice.swift
Sources/SATSCore/Components/NoticeView/NoticeModifier.swift
Sources/SATSCore/Components/NoticeView/NoticeView.swift

This PR adds
```
View.inlineNotice(_ notice: Binding<Notice?>, edge: Notice.Edge = .top)
```
To add a message overlay when needed, good for inline errors.
The way you create the `Notice` object looks like:
```swift
Notice.success(title: "This went ok!")
Notice.warning(title: "Are you sure about this?")
Notice.error(title: "These are not the droids you are looking for")
```
⚠️ When reviewing, take a look at the options when creating a notice.
⚠️ Also I feel the `Notice` concept, `.inlineNotice` is somewhat inconsistent across the implementation so feel free to suggest (with examples of usage), better names for these parts of the feature.
⚠️ There is one behavior that is not solved and it's just a issue in the demo: when manually dismissing a notice and showing a new one just after, it may …

Feature: inline notice

---

DemoApp/DemoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Sources/SATSCore/DNA/Font/SATSFont-SwiftUI.swift
Sources/SATSCore/DNA/Font/SATSFont.swift

This depends on https://github.com/healthfitnessnordic/SATSType-iOS/pull/1
The way to support custom fonts with dynamic type changed in iOS 14
https://www.hackingwithswift.com/quick-start/swiftui/how-to-use-dynamic-type-with-a-custom-font
I could have added support for iOS 13 as well, but I opted not to, as
the idea is to drop iOS 13 soon.

Improvement: support for Dynamic Type for iOS 14+

---

DemoApp/DemoApp/Views/Components/TopBarView/TopBarDemoView.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton-SwiftUI.swift
azure-devops/azure-pipelines-test.yml

I notice if we change a given button from a primary to a secondary style,
the loading indicator is not visible, this is because:
1. if the button was in `.secondary` style
2. we show the indicator (with a blue color on top)
3. we change the button to `.primary` style
4. we set the button to `loading`, but we don't see the indicator.
The indicator is still present, but not visible as the indicator style doesn't get
refreshed when changing the button's style.
Then the solution is to use the `style.name` as `id` to make the spinner refresh
when the style is changed.

Fix: changing the button style updates the spinner

---

DemoApp/DemoApp/Views/Components/NoticeView/NoticeDemoView.swift
Sources/SATSCore/Components/NoticeView/Notice.swift
Sources/SATSCore/Components/NoticeView/NoticeView.swift
azure-devops/azure-pipelines-test.yml

When errors occur and we use notice, we may want to add a retry button to the error case of notices
This will be used in the new friend's profile
If an error has the `onRetry` parameters it won't autoDismiss.

Improvement: allow to "retry" on error notices

---

Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-Types.swift
Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift
Sources/SATSCore/Extensions/SwiftUI/Backport/Backport.swift

I previously shared this article https://davedelong.com/blog/2021/10/09/simplifying-backwards-compatibility-in-swift/
and while working on the new booking UI I started needing support for the `.searchable` modifier which
is only available in iOS 15.
I took some of the modifiers that I did and I included them in the backport type.
Check the individual commits for details.

Feature: backport modifiers

---

Sources/SATSCore/Extensions/SwiftUI/ViewData/AlertViewData.swift

When we want the user to be clearly aware of their actions within an alert, a possibility to add a destructive typed action button could be useful. This PR adds a "ActionButtonStyle" enumeration argument to AlertViewData within the initializer. Default is default and are therefore not destroying existing declarations.

Destructive alert type

---

Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift

support for the .refreshable modifier which is only available in iOS 15.

Feature: add refreshable backport view modifier

---

DemoApp/DemoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift

"We’ll permanently stop accepting DSA keys. RSA keys uploaded after the cut-off point above will work only with SHA-2 signatures (but again, RSA keys uploaded before this date will continue to work with SHA-1). The deprecated MACs, ciphers, and unencrypted Git protocol will be permanently disabled." - 25.03.2022, Github ( https://github.blog/2021-09-01-improving-git-protocol-security-github/ )

Internal: changed url scheme for fetching sats type

---

Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift
Sources/SATSCore/Extensions/SwiftUI/Backport/PullToRefreshContainer/PullToRefreshContainer.swift

This is a change i had to make because https://github.com/healthfitnessnordic/Sats-Member-App-iOS/pull/1060 was blocked by another xcode issue.
Then the app still needs a public version of this component

Fix: make `PullToRefreshContainer` public again

---

Sources/SATSCore/Assets/Colors.xcassets/UI/graphicalElements3.colorset/Contents.json

The dark mode color for graphical elements 3 does not match the design system in Figma and results in a UI which looks strange. Fixed by modifying the colors alpha channel.
| <img src="https://user-images.githubusercontent.com/57347029/159504673-42cf33a8-6163-47a1-a0b5-aeccd930191c.PNG"> | <img src="https://user-images.githubusercontent.com/57347029/159668114-fa9cc8ff-9c89-4328-8489-5999566af0a7.PNG"> |

Fix: update dark mode color of graphical elements

---

GitHub/PULL_REQUEST_TEMPLATE.md

Based on https://github.com/finn-no/FinniversKit/blob/master/PULL_REQUEST_TEMPLATE.md and our discussions in the iOS team
Add an initial version of the PR template.
The idea when doing a PR is to remove sections that don't apply and fill what it makes sense.
Since this is a team effort, I expect all iOS devs in the team to review/approve this PR.
Please comment if you think anything is missing or if you have suggestions

Internal: create PR template

---

Sources/SATSCore/DNA/Spacings/Spacings.swift

[Figma link](https://www.figma.com/file/WzKCwRY09zn4rzRVfY0YvdRt/sats-ds-styles?node-id=341%3A0)
Since we often are using rounded corners on components and cards, we need a standard for different radiuses. 
Adds three different radiuses; Small (8 pts), medium (12 pts) and large (24 pts)
Minor change - This change does not affect existing logic in SATS Core and SATS Member app

Feature: corner radius

---

.github/CODEOWNERS
Sources/SATSCore/Assets/Colors.xcassets/On/Primary/onPrimaryDisabled.colorset/Contents.json
Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift

- Update the `onPrimaryDisabled` color to #878F97
- Add `listRowSeparatorTint`
Patch
This affect primary buttons for example
|:----:|:-----:|
| <img width="564" alt="disabled button - before" src="https://user-images.githubusercontent.com/167989/166242062-81682062-8975-4cc4-a004-6a91f2c2e32a.png"> | <img width="671" alt="disabled button - after" src="https://user-images.githubusercontent.com/167989/166242045-471537e6-b578-42f0-9f05-49db1e334b48.png"> |

Improvements: tweaks for GX booking

---

DemoApp/DemoApp/Views/DNA/ColorDemoView.swift
Sources/SATSCore/Assets/Colors.xcassets/UI/graphicalElements4.colorset/Contents.json
Sources/SATSCore/DNA/Colors/ColorName.swift
Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift
Sources/SATSCore/DNA/Colors/UIKit-Color.swift
Tests/SATSCoreTests/ColorsTests.swift

There is currently an issue in discover where this happens in dark mode.
Add new color graphicalElements4.
This is how the icon will look with the new color.

Internal: add color GraphicalElements4

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp/App/DemoApp.swift
DemoApp/DemoApp/Views/Components/DatePickerView/DatePickerDemoView.swift
Sources/SATSCore/Components/DatePickerView/DatePickerHelper.swift
Sources/SATSCore/Components/DatePickerView/DatePickerView.swift
Sources/SATSCore/Components/DatePickerView/HorizontalDaysList/HorizontalDaysList.swift
Sources/SATSCore/Components/DatePickerView/Subviews/DatePickerView-WeekAndDayView.swift
Sources/SATSCore/Components/DatePickerView/Subviews/DatePickerView-WeekDayLabel.swift
Sources/SATSCore/Components/DatePickerView/Subviews/DatePickerView-WeekdaysView.swift

The calendar component that we created was fit mostly for PT, not GX.
As the GX calendar required some special behavior.
- Add another component `DatePickerView.HorizontalDaysList` that can be used for the behavior that GX wants
- Adjust `DatePickerHelper` that allows to inject today's date for testing purposes
- Fix the DemoApp's type name
Minor
https://user-images.githubusercontent.com/167989/170026683-cb8631cc-ffb7-49b1-a56b-e9a675fa9fe7.mp4

Feature: calendar component for GX booking

---

Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift
Sources/SATSCore/Extensions/SwiftUI/ViewModifiers/OnSearchFocusedModifier.swift

We will want to expand the bottom sheet when the user taps on the search bar in the filters
- Add `View.onSearchFocused` modifier
- Add back-ported variant
minor
This will be used in a new PR in the main app

Feature: onSearchFocused modifier

---

DemoApp/DemoApp/Views/Components/NoticeView/NoticeDemoView.swift
Sources/SATSCore/Components/NoticeView/Notice.swift
Sources/SATSCore/Components/NoticeView/NoticeView.swift

To make the notice more generic and to make use of it in other cases than just where retry is applicable.
- Rename from retry to action
- This will break the member app, but I'll update everything before merging anything.
Breaking change

Internal: Rename `retry` to `action` in the notice

---

DemoApp/DemoApp/Views/DNA/ColorDemoView.swift
Sources/SATSCore/Assets/Colors.xcassets/UI/graphicalElements5.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/UI/graphicalElements6.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/UI/graphicalElements7.colorset/Contents.json
Sources/SATSCore/DNA/Colors/ColorName.swift
Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift
Sources/SATSCore/DNA/Colors/UIKit-Color.swift
Tests/SATSCoreTests/ColorsTests.swift

Figma had colors that weren't in Core package
- Added colors for.
- `graphicalElements5`
- `graphicalElements6`
- `graphicalElements7`
- Update tests
- Minor

Internal: Add missing colors for graphical elements 5,6 and 7

---

Sources/SATSCore/Components/RadioGroup/RadioGroup.swift

According to design a radio group should use a divider between rows of radio buttons.
Add a divider between rows except for the last. This behaviour mimics how `List` works when the separator is visible. 
I opted to NOT use `List` to get this behaviour for free since this would cause issues when using RadioGroup inside a List or a ScrollView.
This is a patch.
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-09-20 at 18 56 30](https://user-images.githubusercontent.com/57347029/191320123-23f69240-475b-4514-a39e-3b25bfb7298f.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-09-20 at 18 56 06](https://user-images.githubusercontent.com/57347029/191320167-072b7bff-e516-4421-9f71-76538eeccdef.png) |

Improvement: use dividers in RadioGroup component

---

DemoApp/DemoApp/Views/Components/RadioGroupView/RadioGroupDemoView.swift

The word was written incorrectly.
Change “Strenght” typo to “Strength”.
Probably just a patch.

Fix: Typo in RadioGroupView Demo

---

Sources/SATSCore/DNA/Font/SATSFont-Weight.swift

Need a font weight that is not specified in SATSCore
By adding an initialiser, we open up the possibility to change the font weight as desired
We can now add our own weight, ex:
```swift
extension SATSFont.Weight {
static let italic = SATSFont.Weight(name: "SATS italic", font: InterFont.boldItalic)
}
```
usage:
```swift
Text(viewData.welcomeTitle)
.satsFont(.h2, weight: .italic)
```
Minor

Feature: expose initializer for `SATSFont.Weight`

---

DemoApp/DemoApp/Views/DNA/ColorDemoView.swift
Sources/SATSCore/Assets/Colors.xcassets/Action/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/Action/action.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/Action/actionDisabled.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/Action/actionHighlight.colorset/Contents.json
Sources/SATSCore/DNA/Colors/ColorName.swift
Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift
Sources/SATSCore/DNA/Colors/UIKit-Color.swift
Tests/SATSCoreTests/ColorsTests.swift

A visual problem we have with colors in the app is that we don't use a propper `accentColor`.
Then, elements in for example: navigation bar or other plain text buttons are not clearly indicated as clickable content
A proper way to do this would be to have a proper accent color like the Apple Store App
Our theme's primary color is not intended/does not work as to show this clickable text, then it's not suited as a primary color. Noes does our selection color.
This PR adds a new color named **action** color (with the highlighted/disabled variants)
This color shows the user where it's appropriate to tap for actions to happen when it comes to plain text

Feature: Action theme colors

---

DemoApp/DemoApp/Views/BasicComponents/SATSButtonDemoView.swift
DemoApp/DemoApp/Views/BasicComponents/SATSButtonSwiftUIDemoView.swift
DemoApp/DemoApp/Views/UIKit Demo/UIKitDemoView.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton-Size.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton-SwiftUI.swift

The design system has updated the button sizes, SATSCore needs to reflect that
Changes reviewed with magnus.
- Remove `.compact` button size
- Update the parameters for the `.basic` size, which is more like the `.compact` size was
- Update the parameters for the `.large` size
- Update to the right weight for the font for buttons `.emphasis`
**breaking** change
| | Before | After |
|:---| --- | --- |
| Basic Size | <img width="564" alt="basic - 01" src="https://user-images.githubusercontent.com/167989/196154339-71497e50-4d1f-4950-a38d-b08d11e9637e.png"> | <img width="564" alt="basic - 02" src="https://user-images.githubusercontent.com/167989/196154334-4bd9d39b-8f26-4042-9a5f-a3b78f8a613b.png"> |
| Large Size | <img width="564" alt="large - 01" …

Improvement: update button styles

---

DemoApp/DemoApp/Views/Components/NoticeView/NoticeDemoView.swift
Sources/SATSCore/Components/NoticeView/Notice.swift
Sources/SATSCore/Components/NoticeView/NoticeView.swift

In darkmode, some configurations were not that legible.
Then Magnus updated the styling for the notice
> **Warning**: this depends on #118 as I want to release both breaking changes together
- Remove unnecessary properties from `Notice`
- Update the styling for `NoticeView`
- Add `Notice.info` styling
**breaking change**
| --- | --- |
| <img width="872" alt="notice - old" src="https://user-images.githubusercontent.com/167989/200526858-82aa4d5c-1b46-4698-93d1-343c8df8ab54.png"> | <img width="872" alt="notice - new" src="https://user-images.githubusercontent.com/167989/200526842-68140c6c-c6fa-44a0-a723-6f9f9db36b6c.png"> |

Improvement: update notice design

---

Sources/SATSCore/Assets/ThemeColors.xcassets/Blue Theme/Primary/bluePrimary.colorset/Contents.json
Sources/SATSCore/Assets/ThemeColors.xcassets/Blue Theme/Primary/bluePrimaryHighlight.colorset/Contents.json

The previous primary dark color was not very accessible
patch
| --- | --- |
| <img width="384" alt="before" src="https://user-images.githubusercontent.com/167989/201938002-05781165-d074-44bd-85da-bcb95b1aafe7.png"> | <img width="384" alt="after" src="https://user-images.githubusercontent.com/167989/201938011-00dd6f74-4390-4154-9c91-374d7ab6e5a1.png"> |

Improvement: adjust primary dark color

---

Sources/SATSCore/Assets/ThemeColors.xcassets/Blue Theme/Navigation/blueNavigation.colorset/Contents.json

from `#9EC3FF` to `#549BDE`
This should match what we changed for the primary color in dark mode
This is a continuation from what I did in #121 
These colors should match, otherwise we end-up with UI like:
Then it looks weird when `#2` is the same but `#1` is different
patch

Fix: update navigation color value for dark mode

---

Sources/SATSCore/Assets/Colors.xcassets/Background/backgroundSurfaceSecondary.colorset/Contents.json
Sources/SATSCore/Assets/Colors.xcassets/On/background/onBackgroundSecondary.colorset/Contents.json

The colours for **background surface secondary** and **on background surface secondary** were updated in Figma.
Update colour for **background surface secondary** and **background surface secondary** 
This is a patch

Improvement: update colors for background surface secondary

---

Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift

iOS 16 introduces a neat modifier which allows us to dismiss the keyboard when the user scrolls. This can be useful for the workout logger and potentially other features.
Add a backport for `scrolldismissesKeyboard(:visibility)`. this method accepts a parameter which is also only available for iOS 16, which means I needed to create a custom object which mirrors it.
This is a minor change

Internal: add backport for scrollDismissesKeyboard

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/SATSCore/BasicComponents/SATSGradient/View-SATSGradient.swift
Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift
Sources/SATSCore/Extensions/SwiftUI/Binding-Extensions.swift

There have been some generic stuff that should have been moved from the main app.
- Move back ported methods
- Move SATSGradient
- Add `Binding.map` extension
minor

Improvement: move types from the main app

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
DemoApp/DemoApp/Views/Components/ModernErrorView/ModernErrorDemoView.swift
DemoApp/DemoApp/Views/ContentView.swift
Sources/SATSCore/BasicComponents/SATSGradient/View-SATSGradient.swift
Sources/SATSCore/Components/ErrorView/ErrorView.swift
Sources/SATSCore/Components/ModernErrorView/ModernErrorView.swift
Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift
Sources/SATSCore/Extensions/SwiftUI/Binding-Extensions.swift

> **Warning**: built on top of #126, review that one first
Our existing `ErrorView` is built for UIKit, so when using it in SwiftUI we need to wrap it into a `SimpleViewRepresentable`, which is a bit unnecessary, when we mostly use SwiftUI in the main app.
Also, the design of that error view was a bit out of date and could use some love.
This `ModernErrorView` is intended as a full screen error component. Otherwise, use the `Notice` modifier instead.
- Add `ModernErrorView` + Demo view
- Add `ErrorViewData.previewValue` factory method
minor
| ErrorView | ModernErrorView |
| --- | --- |
| <img width="565" alt="old" src="https://user-images.githubusercontent.com/167989/207825044-449b6766-731f-4189-b480-0b905781a393.png"> | <img width="565" alt="modern" …

Feature: modern error view

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp/Views/BasicComponents/SATSCellDemoView.swift
DemoApp/DemoApp/Views/ContentView.swift
Package.resolved
Sources/SATSCore/BasicComponents/SATSCell/SATSCell-BasicCell.swift
Sources/SATSCore/BasicComponents/SATSCell/SATSCell.swift

We tend to not use `List` in the main app.
We tend to favor custom made list for most use cases.
For that, we needed a way to generally create custom table cells.
Now, there is a lot of common and optional elements for the cell
Add `SATSCell.BasicCell` with its demo view.
The design of the SATSCell.BasicCell element can be found in https://github.com/sats-group/SATSCore-iOS/commit/24bc78698c5b51db98b2674dfe71184fa6e149ed
minor
The `SATSCell.BasicCell` can be stylized as follows
| Light | Dark |
|:----:|:-----:|
| <img width="565" alt="Screenshot 2023-01-23 at 13 07 38" src="https://user-images.githubusercontent.com/167989/214035957-3943cb43-bb2e-4198-b281-a6cd93a7b555.png"> | <img width="565" alt="Screenshot 2023-01-23 at 13 07 40" …

Feature: `SATSCell.BasicCell`

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp/Views/ContentView.swift
DemoApp/DemoApp/Views/DNA/CornerRadiusDemoView.swift
DemoApp/DemoApp/Views/DNA/SpacingDemoView.swift

I noticed we had a spacing section that said:
> ⚠️ We should totally have constants here!
- Add demo view for spacing
- Add demo view for corner radius
patch I guess

Internal: spacing and corner radius demo views

---

DemoApp/DemoApp/Views/Components/ScrollReaderView/ScrollReaderDemoView.swift
DemoApp/DemoApp/Views/ContentView.swift
Sources/SATSCore/Components/ScrollReaderView/ScrollViewOffsetReader.swift

SwiftUI has type called `ScrollViewReader` so our `ScrollReaderView` was not a good name.
- Update the name of the _public_ type and the demo
- Add the capability to use `ScrollViewOffsetReader` in horizontal mode as well
⚠️ **Breaking change**
Users of the library just need to replace calls to `ScrollViewReader` with `ScrollViewOffsetReader`. The rest of the API stays the same

Improvement: rename `ScrollReaderView` to `ScrollViewOffsetReader`

---

Sources/SATSCore/Components/NoticeView/Notice.swift

So we can create error notices that can be retried
patch

Improvement: expose `actionTitle` and `action` on `Notice.error`

---

Sources/SATSCore/Extensions/SwiftUI/ViewData/ActionSheetViewData.swift

We may also want destructive actions in actionSheets
Add new parameter to `ActionViewData`, `isDestructive: Bool`, with default value `false`
minor

Improvement: allow to mark an `ActionSheetViewData` `Action` as `isDestructive`

---

DemoApp/DemoApp/Views/BasicComponents/CustomAsyncImageDemoView.swift
Sources/SATSCore/BasicComponents/CustomAsyncImage/CustomAsyncImage.swift
Sources/SATSCore/BasicComponents/CustomAsyncImage/ImageClient.swift
Sources/SATSCore/BasicComponents/CustomAsyncImage/ImageViewModel.swift

It's nice to use the `.task` so we can handle automatically the request cancellation,
also improving the feeling of the component by animating the state transitions
- Make the protocol `ImageClient` use _async/await_ instead of _closures_ to load images
- Use `.task` to load the image if needed for `CustomAsyncImage`
- Animate transitions between image states
**Breaking change**
The configuration protocol `ImageClient` changed, to use a `async` version instead of a closure based approach.
```diff
public protocol ImageClient {
-    func loadImage(with url: URL, onCompletion: @escaping (Result<Image, Error>) -> Void)
+    func loadImage(with url: URL) async throws -> Image
}
```
https://user-images.githubusercontent.com/167989/218675454-8edec32e-16a7-47fc-a626-d02dafe2a313.mp4

Improvement: custom async image modernization

---

DemoApp/DemoApp/Views/Components/NoticeView/NoticeDemoView.swift
Sources/SATSCore/Components/NoticeView/Notice.swift
Sources/SATSCore/Components/NoticeView/NoticeView.swift

- Make the properties of the notice similar to `ErrorViewData` in Sats-MemberApp. Therefore, rename `explanation` to `message`
- The current notice has an optional `explanation` and a required `title`. We can argue that a title without content doesn't make sense, but an explanation makes sense without a title.
- Rename `explanation` to `message` as requierd property.
- `title`is now optional.
breaking change
|![image](https://user-images.githubusercontent.com/9019310/225064302-bbed4026-887d-4e42-97f6-3f1105283e32.png)|![image](https://user-images.githubusercontent.com/9019310/225063600-6630eeb9-a1bf-4ece-814d-688bb6beffa4.png)|

Improvement: Notice - make message required and title optional

---

Sources/SATSCore/BasicComponents/SATSButton/SATSButton-SwiftUI.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton.swift

We want our core buttons to have a rounded rectangle shape, as we do on the web. 
Patch

Improvement: Rounded rectangle buttons

---

Sources/SATSCore/BasicComponents/SATSCell/SATSCell-BasicCell.swift
Sources/SATSCore/Extensions/SwiftUI/ViewModifiers/ImageSizeClassHeightModifier.swift

A convenience modifier to give a constant height that applies for the given horizontal size class,
then we can specify for example:
- 240 pts for the compact horizontal size class
- 360 pts for the regular horizontal size class
- Add `View.sizeClassHeight` modifier
- Allow setting the background color for SATSCell.BasicCell
minor

Feature: view sizeClassHeight modifier

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp/Views/Components/ProfilePictureView/ProfilePictureDemoView.swift
DemoApp/DemoApp/Views/ContentView.swift
Sources/SATSCore/Components/ModernErrorView/ModernErrorView.swift
Sources/SATSCore/Components/ProfilePictureView/ProfilePictureView.swift

We use this small composed view everywhere, it deserves to be in the library,
specially when the clipping of the image can be done "wrong"
```swift
// ✅ OK
public var body: some View {
CustomAsyncImage(imageData) { image in
image
.resizable()
.aspectRatio(contentMode: .fill)
}
.controlSize(spinnerSize)
.clipShape(Circle())
.frame(size: size)
}
```
```swift
// ❌ not ok for the loading state
public var body: some View {
CustomAsyncImage(imageData) { image in
image
.resizable()
.aspectRatio(contentMode: .fill)
.clipShape(Circle())
}
.controlSize(spinnerSize)
.frame(size: size)
}
```
it also controls the size of the spinner too
- Adds `ProfilePictureView` with demos and so on
- Removes background from `ModernErrorView`
minor

Feature: ProfilePicture component

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
DemoApp/DemoApp/Utils/DemoWrapperView.swift
DemoApp/DemoApp/Views/Components/BannerNotice/BannerNoticeDemoView.swift
Sources/SATSCore/Components/BannerNotice/BannerNotice.swift
Sources/SATSCore/DNA/Font/SATSFont-SwiftUI.swift
Sources/SATSCore/Extensions/SwiftUI/Binding-Extensions.swift

SATSFont.font internally uses `UIFontMetrics` to determine the sizes of
the font adjusted to font families for dynamic type.
**But** since this lives in UIKit-land, this value doens't get
recomputed when the environment changes (in a SwiftUI context), but only
when the UITraitCollection of a view controller changes.
In the case of SwiftUI previews, only the environment changes for
previews, that's the reason we were not seeing the changes in font size
when we did the "show accessibility variants" in previews.
Now, by using `Font.custom` the values do get recomputed when the
environment's `dynamicTypeSize` changes.
patch

Fix: dynamic type for swift UI

---

Sources/SATSCore/Components/BannerNotice/BannerNotice.swift

Today we use a spacer() in an HStack to push the button to the trailing end. Then we do not have control over the layout in terms of spacing between the text and button. 
Adds a modifier .frame(maxWidth: infinity, aligment: .leading) to the text content
Patch
| --- | --- |
|![Skjermbilde 2023-09-04 kl  12 09 46](https://github.com/sats-group/SATSCore-iOS/assets/9019310/017a2972-62fa-4e0d-8f15-a694dea0c094)|![Skjermbilde 2023-09-04 kl  12 08 42](https://github.com/sats-group/SATSCore-iOS/assets/9019310/2f9d3123-3086-47ae-8a36-0d400f97696b)|

Improvement: Control the spacing between text and button in `BannerNotice`

---

Sources/SATSCore/Components/NoticeView/Notice.swift

There is a need to add an action to a warning notice in the member app. 
- Adds new arguments to Notice.warning() initializer. 
Minor

Improvement: Adds `actionTitle` and `action` to Notice.warning

---

DemoApp/DemoApp.xcodeproj/project.pbxproj
DemoApp/DemoApp.xcodeproj/xcshareddata/xcschemes/DemoApp.xcscheme
DemoApp/TestPlans/SATSCoreOnWatchOS.xctestplan
Package.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton-Size.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton-Style.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton-SwiftUI.swift
Sources/SATSCore/BasicComponents/SATSButton/SATSButton.swift
Sources/SATSCore/BasicComponents/SATSLabel/SATSLabel.swift
Sources/SATSCore/Components/BannerNotice/BannerNotice.swift
Sources/SATSCore/Components/ErrorView/ErrorView.swift
Sources/SATSCore/Components/LoadingView/LoadingView.swift
Sources/SATSCore/Components/ModernErrorView/ModernErrorView.swift
Sources/SATSCore/Components/NoticeView/Notice.swift
Sources/SATSCore/Components/NoticeView/NoticeModifier.swift
Sources/SATSCore/Components/NoticeView/NoticeView.swift
Sources/SATSCore/Components/RoundLoadingView/RoundLoadingView.swift
Sources/SATSCore/Components/WheelPickerView/WheelPickerView-Config.swift
Sources/SATSCore/Components/WheelPickerView/WheelPickerView.swift
Sources/SATSCore/DNA/Colors/UIKit-Color.swift
Sources/SATSCore/DNA/Icons/UIKit-Icon.swift
Sources/SATSCore/Extensions/SwiftUI/Representable/ShareSheet.swift
Sources/SATSCore/Extensions/SwiftUI/Representable/SimpleControllerRepresentable.swift
Sources/SATSCore/Extensions/SwiftUI/Representable/SimpleRepresentable.swift
Sources/SATSCore/Extensions/UIKit/UIView-Layout.swift
Tests/SATSCoreTests/ColorsTests.swift

To revamp the watchOS app we also want to use the design system, mainly colors and so on for watchOS
- Add support for watchOS for SATSCore
- Add conditional compilation for UIKit components
- Update SATSType from 0.0.3 to 0.0.4
- Test SwiftUI colors instead of UIColor, so It can run for iOS and watchOS targets
- Add a TestPlan to run test on watchOS
Minor

Feature: watchOS support for SATSCore

---

Sources/SATSCore/Extensions/SwiftUI/View-Utilities.swift

- Move `View` extensions from the app
- `satsShadow`
- `satsCard`
- Add `View` extensions
- `ignoreOtherTaps`
- `readableWidth`
- `roundedBorder`
minor

Feature: more `View` extensions
