sats-group/SATSCore-iOS

DemoApp/DemoApp.xcodeproj/project.pbxproj, DemoApp/DemoApp/Views/Components/LoadingView/LoadingDemoView.swift, DemoApp/DemoApp/Views/ContentView.swift, Sources/SATSCore/Components/LoadingView/LoadingView.swift, Sources/SATSCore/Extensions/SwiftUI/Representable/ShareSheet.swift
- Add SwiftUI representable implementation for ShareSheet
- Add `LoadingView`
=> Component: LoadingView and ShareSheet

DemoApp/DemoApp.xcodeproj/project.pbxproj, DemoApp/DemoApp/Views/Components/TabSelectionView/TabSelectionDemoView.swift, DemoApp/DemoApp/Views/ContentView.swift, Sources/SATSCore/Components/TabSelectionView/TabSelectionView.swift
=> Feature: tab selection view

Sources/SATSCore/Assets/Colors.xcassets/Background/backgroundPrimary.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Background/backgroundSecondary.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Background/backgroundSurface.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Gold Theme/Background Top/goldGradientEnd.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Gold Theme/Background Top/goldGradientStart.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Platinum Theme/Background Top/platinumGradientEnd.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Platinum Theme/Background Top/platinumGradientStart.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Silver Theme/Background Top/silverGradientEnd.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Silver Theme/Background Top/silverGradientStart.colorset/Contents.json
- primary
- secondary
- surface
- top and bottom for themes
We are descending more and more into darkness, moving away from 50
shades of gray and embracing the true darkness (black #000)
=> Internal: Update background color values for dark mode

Sources/SATSCore/Assets/Colors.xcassets/Main/CTA/cta.colorset/Contents.json
=> Update CTA default light

Sources/SATSCore/Assets/Colors.xcassets/Main/Secondary/secondary.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Main/Secondary/secondaryDisabled.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Main/Secondary/secondaryHighlight.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Blue Theme/Primary/bluePrimaryDisabled.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Gold Theme/Background Top/goldGradientEnd.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Gold Theme/Primary/goldPrimary.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Gold Theme/Primary/goldPrimaryDisabled.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Gold Theme/Primary/goldPrimaryHighlight.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Platinum Theme/Primary/platinumPrimary.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Platinum Theme/Primary/platinumPrimaryDisabled.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Platinum Theme/Primary/platinumPrimaryHighlight.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Silver Theme/Background Top/silverGradientStart.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Silver Theme/Primary/silverPrimary.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Silver Theme/Primary/silverPrimaryDisabled.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Silver Theme/Primary/silverPrimaryHighlight.colorset/Contents.json, Sources/SATSCore/Assets/ThemeColors.xcassets/Silver Theme/silverSelection.colorset/Contents.json
We needed to sync colors for the different themes.
Also, updated the secondary colors in dark mode to their new values.
=> Internal: update theme colors

Sources/SATSCore/Components/NoticeView/NoticeView.swift
A request from Magnus to adjust the UI of NoticeView. Figma is a mess right now but here is a [link](https://www.figma.com/file/CK0m9op0F5ij5ixSvKZe4K0g/sats-app-components?node-id=4809%3A10) to the component.
=> Improvement: Adjust UI of NoticeView

Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift, Sources/SATSCore/DNA/Colors/UIKit-Color.swift
I introduced this warnings in #65 which i didn't notice before, then i
fix them now
=> Internal: Fix Swiftlint warnings

DemoApp/DemoApp/Views/DNA/ColorDemoView.swift, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalDeleteText.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalError.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalErrorText.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalSuccess.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalSuccessText.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalWarningText.colorset/Contents.json, Sources/SATSCore/DNA/Colors/ColorName.swift, Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift, Sources/SATSCore/DNA/Colors/UIKit-Color.swift, Tests/SATSCoreTests/ColorsTests.swift
Changes in this PR:
- Update signal colors from Figma
- Adds text colors for signals from Figma
- Adds text colors for signals in DemoApp
=> Update colors [NMA-2946]

DemoApp/DemoApp/Views/DNA/ColorDemoView.swift, Sources/SATSCore/Assets/Colors.xcassets/Challenges/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Challenges/challengeFailed.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Challenges/challengeInProgress.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Challenges/challengeNotDone.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Challenges/challengeSuccess.colorset/Contents.json, Sources/SATSCore/DNA/Colors/ColorName.swift, Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift, Sources/SATSCore/DNA/Colors/UIKit-Color.swift, Tests/SATSCoreTests/ColorsTests.swift
=> Internal: Add challenge colors

Sources/SATSCore/DNA/Spacings/Spacings.swift
From now on these are the spacings we'll strive to use, and that design also will use in the design system.
=> Improvement: Created Spacings

DemoApp/DemoApp/Views/Components/DatePickerView/DatePickerDemoView.swift, Sources/SATSCore/Components/DatePickerView/DatePickerHelper.swift, Sources/SATSCore/Components/DatePickerView/DatePickerView.swift, Sources/SATSCore/Components/DatePickerView/Subviews/DatePickerView-MonthView.swift, Sources/SATSCore/Components/DatePickerView/Subviews/DatePickerView-WeekView.swift, Sources/SATSCore/Components/DatePickerView/Subviews/DatePickerView-WeekdaysView.swift
- Updated colors
- Changed to chevron button until we have drag functionality
=> Task: Datepicker refinements

Sources/SATSCore/Components/DatePickerView/DatePickerView.swift
=> Internal: Fix touch area for date picker toggle

DemoApp/DemoApp/Views/Components/DatePickerView/DatePickerDemoView.swift, Sources/SATSCore/Components/DatePickerView/DatePickerView.swift
- Expose view data properties to users of SATSCore
- Fix toggle button being overlapped by vertically stacked content
| <img width="564" alt="before" src="https://user-images.githubusercontent.com/167989/156763975-8b6a7e8b-16ba-47fc-9517-087972d6945e.png"> | <img width="564" alt="after" src="https://user-images.githubusercontent.com/167989/156763941-219d6494-9964-44a6-8bee-cc3baa2c2c64.png"> |
=> Improvement: date picker component refinements

Sources/SATSCore/Extensions/SwiftUI/Backport/Backport-ViewExtensions.swift, Sources/SATSCore/Extensions/SwiftUI/EdgeInsets.swift, Sources/SATSCore/Extensions/UIKit/UIEdgeInsets.swift
This PR does two things:
- Adds backport for listRowSeparator. I tried some experiments to make this work on iOS 14. Let me know if you have a solution for this.
- Adds custom initializers for EdgeInsets.
=> Feature: Add backport and initializers

Sources/SATSCore/Extensions/SwiftUI/Backport/PullToRefreshContainer/PullToRefreshContainer.swift
with the work done in #85, I made the `PullToRefreshContainer` API
compatible with the `.refreshable` modifier.
To do that, i had to move the `isLoading` state, from the caller to the
internal state of the component.
The function that is passed as `onReload` to `PullToRefreshContainer` is
marked as async.
I was calling `await onReload()` to set the `isLoading = false`
**after the async onReload returned**, **BUT!!** since we had code that
was not using functions that use the new `async` annotation with the
`.refreshable` modifier, but completion hanlders in some cases. We
cannot rely on `await` then.
That caused multiple network calls, when performing the pull to refresh
gesture.
Now. Instead of relying on the `onReload` returning synchronously,
`isLoading` is taking in account the …
=> Fix: `PullToRefreshContainer` reload behavior (iOS 14)

DemoApp/DemoApp/Views/Components/TopBarView/TopBarDemoView.swift, Sources/SATSCore/Extensions/UIKit/UIButton-Common.swift
They are unnecessary large
- Make the size `32` instead of `36`
Patch
=> Improvement: size of navigation bar buttons

Package.resolved, Sources/SATSCore/DNA/Spacings/Spacings.swift
Need resolution of 2 pixels
added spacingXXXS
=> Improvement: add new spacing constant

Sources/SATSCore/Extensions/SwiftUI/ViewData/AlertViewData.swift
In cases where we want to have a second option that is not "cancel"
Adds optional parameters specifying an alert button 
Minor change
=> Feature: AlertViewData - Adds option for a secondary alert button

DemoApp/DemoApp.xcodeproj/project.pbxproj, DemoApp/DemoApp/Views/Components/WheelPickerView/WheelPickerDemoView.swift, DemoApp/DemoApp/Views/ContentView.swift, Sources/SATSCore/Components/TabSelectionView/TabSelectionView.swift, Sources/SATSCore/Components/WheelPickerView/WheelPickerView-Config.swift, Sources/SATSCore/Components/WheelPickerView/WheelPickerView.swift, Sources/SATSCore/DNA/Colors/ColorTheme-SwiftUI.swift, Sources/SATSCore/Extensions/SwiftUI/Representable/SimpleControllerRepresentable.swift
Because of feedback that the current way of selecting duration needs to be improved (https://hfnswedenab.atlassian.net/browse/NMA-3755)
A wheel picker for selecting an integer value by turning the wheel to the desired value. This can be extended later to support decimals as well, but for now it's only integers.
[Design](https://www.figma.com/file/kJrZDtTvAZxCpPkXzDoPUe/Untitled?node-id=3%3A2720) - This is first iteration and the tickers are different because of reasons. But I've clearified this with Magnus, so this version is an acceptable first version.
Minor
| Light | Dark |
| --- | --- |
| ![Screenshot 2022-08-25 at 14 54 50](https://user-images.githubusercontent.com/675434/186685844-7b7779f2-f856-422d-bef6-4bec865d422d.png) | ![Screenshot 2022-08-25 at 14 54 …
=> Feature: Wheel picker component

DemoApp/DemoApp.xcodeproj/project.pbxproj, DemoApp/DemoApp/Views/Components/BannerImage/BannerImageDemoView.swift, DemoApp/DemoApp/Views/ContentView.swift, Sources/SATSCore/Components/BannerImage/BannerImage.swift
The new product pages will use this component
- Add `BannerImage` component with its demo view
minor
=> Feature: BannerImage component

Sources/SATSCore/Assets/Colors.xcassets/UI/border.colorset/Contents.json
Changing the color for border in dark mode to match design system, SATSCore needs to reflect that
Change reviewed with magnus.
- Update the `.border` color
patch
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2022-11-07 at 13 25 31](https://user-images.githubusercontent.com/31440186/200309937-625d6356-0308-4d66-878e-ca02a692ef46.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2022-11-07 at 12 50 09](https://user-images.githubusercontent.com/31440186/200306416-707253f7-d92f-4779-a36e-b5d824a449fb.png) |
=> Improvement: Update border color

DemoApp/DemoApp.xcodeproj/project.pbxproj, DemoApp/DemoApp/Views/DNA/ColorDemoView.swift, Sources/SATSCore/Assets/Colors.xcassets/Workout/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Workout/workoutGx.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Workout/workoutGymfloor.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Workout/workoutOwnTraining.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Workout/workoutPt.colorset/Contents.json, Sources/SATSCore/BasicComponents/CustomAsyncImage/CustomAsyncImage.swift, Sources/SATSCore/DNA/Colors/ColorName.swift, Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift, Sources/SATSCore/DNA/Colors/UIKit-Color.swift, Sources/SATSCore/Extensions/SwiftUI/View-Utilities.swift, Sources/SATSCore/Extensions/SwiftUI/View-sizeReader.swift, Tests/SATSCoreTests/ColorsTests.swift
They are part of the new completed workout
Add new workout colors
- Add `alignment` parameter to `View.frame(size:)`
- Have SwiftLint work with mint too
- Add `View.sizeReader` from the app repo
minor
=> Feature: new workout colors

Sources/SATSCore/BasicComponents/SATSButton/SATSButton-Size.swift
=> Improvement: SATSButton size

DemoApp/DemoApp.xcodeproj/project.pbxproj, DemoApp/DemoApp/Views/Components/BannerNotice/BannerNoticeDemoView.swift, DemoApp/DemoApp/Views/ContentView.swift, Sources/SATSCore/Components/BannerNotice/BannerNotice.swift
Its already a listed component in Figma and used several places in Sats-MemberApp
Adds: NoticeBanner with DemoView
Minor
=> Feature: Notice Banner

DemoApp/DemoApp/Views/DNA/ColorDemoView.swift, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalDeleteBackground.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalErrorBackground.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalSuccessBackground.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Signal/signalWarningBackground.colorset/Contents.json, Sources/SATSCore/Assets/Colors.xcassets/Waitlist/waitlistBackground.colorset/Contents.json, Sources/SATSCore/DNA/Colors/ColorName.swift, Sources/SATSCore/DNA/Colors/SwiftUI-Color.swift, Sources/SATSCore/DNA/Colors/UIKit-Color.swift, Tests/SATSCoreTests/ColorsTests.swift
The design system has been updated with new background colors for signals and waitlist.
- Add new colors to assets catalog
- Make new colors available to SwiftUI and UIKit
- Update color tests
- Update demo view
This is a minor change.
=> Feature: Add background colors for signal and waitlist

DemoApp/DemoApp.xcodeproj/project.pbxproj, DemoApp/DemoApp/Views/Components/SectionHeader/SectionHeaderDemoView.swift, DemoApp/DemoApp/Views/ContentView.swift, Sources/SATSCore/Components/SectionHeader/Components/SystemChevron.swift, Sources/SATSCore/Components/SectionHeader/SectionHeader.swift
- New component in the design system
- Adds component
- Adds a demo view
Minor
=> Feature: Section header
